
image: Ubuntu 

stack: jdk 11  

branches:
  only:
    - master 

build: off  

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - ./gradlew test --info -Dselenide.headless=true
  
